### ISSUE TITLE
Any plans for ignite 2.x ?

### ISSUE THREAD

**Issue by hiql** [dexecutor/dexecutor-ignite#2]
I am trying to run the tests under ignite 2.x...
No errors, no exceptions, but the node #4 
How do I fix it?

------------------------------------------------------------------------
erroredCount == 0
getUnProcessedNodesCount == 0
getProcessedNodes == [12, 11, 10, 9, 8, 7, 6, 5, 3, 2, 1, 14, 13]

Path #0
1[] 
2[1] 3[1] 
7[2] 9[2] 8[2] 5[3] 6[3] 
10[9] 
Path #1
11[] 
Path #2
12[] 
13[12] 
4[3, 13] 14[13]

**Comment by mnadeem** [comment]
which test case you are running

**Comment by hiql** [comment]
@mnadeem 
dexecutor-ignite/src/test/java/com/github/dexecutor/ignite/Job.java

it works with ignite 1.9.0, but doesn't work correctly with 2.0.0 or above...

**Comment by mnadeem** [comment]
Apache ignite 2.3.0 has buggy contains and containsAll, will open a ticket with them

**Comment by mnadeem** [comment]
Fixed, will release the version soon 1.1.0

**Comment by mnadeem** [comment]
1.1.0 released with 2.3.0 support

**Comment by hiql** [comment]
I refactored some code
there seems to be no problem with ignite 2.3.0 ...
`
public IgniteExecutionEngine(final DexecutorState<T, R> dexecutorState, final IgniteCompute igniteCompute,
			BlockingQueue<Future<ExecutionResult<T, R>>> completionQueue) {
		checkNotNull(igniteCompute, "Executer Service should not be null");
		checkNotNull(completionQueue, "BlockingQueue should not be null");
		this.dexecutorState = dexecutorState;
		// this.igniteCompute = igniteCompute.withAsync();
		**this.igniteCompute = igniteCompute;**
		this.completionQueue = new LinkedBlockingQueue<>();
	}

	@Override
	public void submit(final Task<T, R> task) {
		logger.debug("Received Task {}", task.getId());
		// this.igniteCompute.call(new SerializableCallable<T, R>(task));
		// igniteCompute.future().listen(newListener());

		**IgniteFuture<ExecutionResult<T, R>> future = this.igniteCompute.callAsync(new SerializableCallable<T, R>(task));
		future.listen(newListener());**
	}

	**private IgniteInClosure<IgniteFuture<ExecutionResult<T, R>>> newListener() {
		return new IgniteInClosure<IgniteFuture<ExecutionResult<T, R>>>() {

			private static final long serialVersionUID = 1L;

			@Override
			public void apply(IgniteFuture<ExecutionResult<T, R>> e) {
				completionQueue.add((ExecutionResult<T, R>) e.get());
			}
		};
	}**

	// private IgniteInClosure<IgniteFuture<Object>> newListener() {
	// 	return new IgniteInClosure<IgniteFuture<Object>>() {

	// 		private static final long serialVersionUID = 1L;

	// 		@SuppressWarnings("unchecked")
	// 		@Override
	// 		public void apply(IgniteFuture<Object> e) {
	// 			completionQueue.add((ExecutionResult<T, R>) e.get());
	// 		}
	// 	};
	// }

`

**Comment by mnadeem** [comment]
There is an issue with Ignite set, queue is fine in Version 2.....

Your changes looks cool too, let me try that.
